version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '9080:9080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
networks:
  jenkins:
volumes:
  jenkins_data:
    driver: local
