version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '5000:5000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local
